#ifndef ENUMGAME_H
#define ENUMGAME_H

enum GameGamestate
{

    #ifdef __NDS__
    GAMEMODE, TITLEMODE, MAPMODE, TELEPORTERMODE, GAMECOMPLETE,  GAMECOMPLETE2, PRELOADER
    #else
    GAMEMODE, TITLEMODE, MAPMODE, TELEPORTERMODE, GAMECOMPLETE,  GAMECOMPLETE2, EDITORMODE, PRELOADER
    #endif

};

#endif /* ENUMGAME_H */
